### ISSUE TITLE
Mobs At Start of EoA Are Mispositioned

### ISSUE THREAD

**Issue by Cistoran** [nnogga/MethodDungeonTools#1]
The first set of mobs in EoA are mispositioned.

Wandering Shellback 1
Wandering Shellback 2
Hatecoil Warrior 1
Hatecoil Warrior 2
Hatecoil Wrangler 1
Hatecoil Stormweaver 1
Hatecoil Warrior 3

Most of them are just shifted to the left quite a bit. See screenshots below for the way they're setup.
https://gyazo.com/ac99a7694c98d3d94ca54f30af447d27
https://gyazo.com/f6db609c4cf03e74befe69f95df6d883

**Comment by nnogga** [comment]
The mobs are correctly positioned, the blizzard map is just not correctly aligned with the ingame world - the road on the map is not where the road is ingame.
https://i.imgur.com/0doYJ3d.jpg
https://i.imgur.com/iV0JMd5.png

**Comment by Heimidall** [comment]
Dungeon: Cathedral of Eternal Night.
Zone: The Emerald Archives.

When you try to select a pack of imps or scanvegers it selects both left and right and the patrollers.

Before clicking
![Before Clicking](https://user-images.githubusercontent.com/18452593/36949451-65ce05b4-1fc7-11e8-806d-8b611f97ad4e.jpg)

After Clicking
![issue_2](https://user-images.githubusercontent.com/18452593/36949465-821518c0-1fc7-11e8-8248-1290b4e196ce.jpg)
