### ISSUE TITLE
unlinked mobs programmed as linked in NL

### ISSUE THREAD

**Issue by Dunao** [nnogga/MethodDungeonTools#10]
![image](https://user-images.githubusercontent.com/37051450/36951498-d10b680c-2004-11e8-9c44-679bc1c849dc.png)
The small crawlers in the red and blue area can be pulled separately from the black ones. i dont't know the exact linking of the mobs, but these 4 can be easily pulled in a 3+1 fashion.

![image](https://user-images.githubusercontent.com/37051450/36951535-33135e6a-2005-11e8-8ba7-192da43b3e9b.png)
these crocodiles are also not completely linked

**Comment by nnogga** [comment]
For ease of use these crawlers willbe seperated into two groups of linked mobs. You can use CTRL+Left Mouse Button to force single select/deselect crawlers.
