### ISSUE TITLE
2.8.6-alpha missing commit

### ISSUE THREAD

**Issue by LordDeimos666** [nnogga/MethodDungeonTools#112]
The version https://github.com/nnogga/MethodDungeonTools/tree/v2.8.6-alpha doesn't have the commit 41fc46a93cfb8453c7950057df9c8b652a68639e that solve the week 8 and 9 affix into it.
Also other commit you have in master branch missing: 4f2b801 4a759e9 0269809

**Comment by nnogga** [comment]
resolved in #115
