### ISSUE TITLE
Suggestion: Opening MDT inside of an instance should default to the instance you're in / also missing rift warden spawns

### ISSUE THREAD

**Issue by Xyxeii** [nnogga/MethodDungeonTools#21]
Like the title says. 

Also to follow up so I don't clog the issues. I think you're missing a Rift Warden in Seat near the 2nd boss. 

-edit. I revisited the Rift Warden spawn thing later and found that there is more potential spawns that aren't currently mapped in the addon. I don't know if this is intentional, but it does change the pulls depending on spawn count. I was attempting to make a preset for each possible route, which is dependent on the spawn of those rifts.

**So far I have these locations as well as some evidence to their existence in m+(in the event you choose to map them):**
-------------------------------------------------------------
**Spawn by the water**

**Map Location:**
![a](https://i.imgur.com/WszVhx1.jpg)

**Evidence:**
![a](https://i.imgur.com/cmurbBY.jpg)

-------------------------------------------------------------
**Spawn in the shadow pool on right side**

**Map Location:**
![a](https://i.imgur.com/fAahXg1.jpg)

**Evidence:**
![a](https://i.imgur.com/AeC7VBU.jpg)

-------------------------------------------------------------
**Spawn Near Boss** (mentioned in the original comment)

**Map Location:**
![a](https://i.imgur.com/Y8QMTv0.jpg)

**Evidence:**
![a](https://i.imgur.com/bTacWcX.jpg)
![a](https://i.imgur.com/JtVEtrW.jpg)

**Comment by nnogga** [comment]
Rift warden spawns have been  hotfixed to only be the 3 that You can see in the addon since a month or two in m+

**Comment by nnogga** [comment]
Defaulting to the current dungeon has been tried and deemed to be more annoying than helpful.
