### ISSUE TITLE
Advanced Mob info

### ISSUE THREAD

**Issue by realJove** [nnogga/MethodDungeonTools#22]
Add info to mob tool tip like dangerous casts. CC Immunity and stuff.
I think this will greatly increase the user base since imo there will be alot of users that dont pre plan pulls (or use preset pulls if that is planned) but need info about specific mobs to focus/care about/how to handle them.
I dont know where you wanna go with that addon. I think that is alot of work and goes more toward some kind of m+ compendium.

**Comment by noisex** [comment]
+ add npcID and/or link to wowhead for getting more info about mobs.

**Comment by nnogga** [comment]
This has been implemented into the newest version. Data is currently being gathered by the userbase.
