### ISSUE TITLE
Errors on logging in and typing /mdt

### ISSUE THREAD

**Issue by Dunao** [nnogga/MethodDungeonTools#23]
downloaded the addon on my laptop to test some stuff while "at work", but i cannot start the addon.

errors on logging in and reloading (all other addons except mdt, bugsack and buggrabber disabled, english client):
error 1: https://pastebin.com/CAT17sYU
error 2: https://pastebin.com/z5LWchqy

errors on typing /mdt and pressing enter ONCE:
error 3: https://pastebin.com/cjHeRws1
error 4: https://pastebin.com/vb75AF46

while pressing enter, the chat-line doesnt disappear (the /mdt i typed) and the addon opens (though without any visible map, see below). pressing enter a second time closes both the addon and the chat-line.

error 4 seems to be the same error as posted in https://github.com/nnogga/MethodDungeonTools/issues/18, but since i got additional errors i opened a new issue. the map isnt showing either. error 4 seems to appear ~ 10 times per second while hovering over the location where the map should be (the now transparent area of the addon).

map not visible:
![image](https://user-images.githubusercontent.com/37051450/37036041-c3b12aac-214e-11e8-9560-44403f590a54.png)

**Comment by Tomsize** [comment]
Try installing Mapster, it fixed this for me.

https://www.curseforge.com/wow/addons/mapster/download/931389
