### ISSUE TITLE
Missing one mob in lower kara?

### ISSUE THREAD

**Issue by zirqz** [nnogga/MethodDungeonTools#24]
![missing journeyman](https://user-images.githubusercontent.com/37120591/37052895-fc298b6e-217a-11e8-9f43-525c0c26d6f3.jpg)

If i am not completely mistaken, there is a Spectral Journeyman missing.

**Comment by Dunao** [comment]
yup, there seems to be one mob missing. 
proof (non-teeming):
![image](https://user-images.githubusercontent.com/37051450/37092216-3653d728-220b-11e8-8d60-e9fc7d49266f.png)
