### ISSUE TITLE
Wrong counts in VotW?

### ISSUE THREAD

**Issue by Dunao** [nnogga/MethodDungeonTools#25]
We just did a VotW key, and at one point the score from AngryKeystones didn't match the score of the mdt addon.
we pulled 6 mobs (see below) and expected to obtain 24 score, but we gained only 16 score.
![image](https://user-images.githubusercontent.com/37051450/37060768-8e553568-2191-11e8-89f1-71adc8ed88a2.png)
Going through the video (clip: https://www.youtube.com/watch?v=E_KX-9p2ae8) i saw, that both fel-infused furies did not add any count when they died (5 sec and 9 sec, you can go frame by frame with "," and "." on youtube). Is the addon wrong, did we encounter a bug or do they really give no count?

**Comment by koolkiwi** [comment]
Hi! I wanted to add to this I just did a key with the following route, however we were short 2%. This was teeming, quaking, fort

duIvfaGnsmBcYTPur7u2l2nPIHrQ63eqgkLk1WPuvoiLQ0XuDosYcPujlMsvSCkLNsbpMGYZPuvnrcqtvPjtG00P6zeDDk0MjvA7eq9zcexMK6WeaJNGQtsPcltX1iLPrOttG6Bu04OK5SyqGfaHmQMfdcZOnBQ1XTBJcjeDmimJ2SPwh3Gr7ri1cSAHOJbHz0Mn164cOrDee1cKo2HGkC6sm4QvBNcwhbb7cdcZOnBQ1XTxD1vWchd6kq2CbRRGvlOyW(mkKq2plDw6S0PtdnKKK40WsNUEAOtsAirsItsw6KjnKfoDnwCCAyjrw60Xjnw6Kin0jjnKizrAKgPqsYKuilYehNKS0zPtI40WsNmPH(XjjlDsKgsdN0yXjfw60PHeXXjrwsJLondn0njjDlsKg9KgnNuOrKmPrJSOrHurJKUE6QOF6I0h6k0LKk6I01txJ(PRqFOBsxs3IUgooPXsNLoPHtdlDYcNKS0jfCsHLon4KjlDAOHojjjooPWsdlDsfoPWsNK44KjlDwCAyXjjloPWIJtwSKflDsAsdnMKKKwKiDrsJUcPqJEYKgrYIglsfjh66jPK(PBsFO50L0OrxKgv01iPiDfsQr3KUgDl6w0vrZqJEAuO5KupndjvOrssv0isxfnA0iPrHKNgt6dnw0qJksss9KijpPrYHuiPKmjPizrsn66jPcPIKM0pjTOljPk64Kkw60XXjvS0plD640LS0PHg64Kflo9HLon0qhNUilooD9S40plDwCAyXjjloDjloDfw60qdDssIKijXPRXItkS440hw6kS0PlPHUgjPRqI0fjn6dPq)401yPtsAirCC6sw6MS0jjnKioDnw6KcnKgooDrw6S40WItswC6IS4KcloDfwC66zXXXXXGRw4ogeq16kagfYXba

**Comment by nnogga** [comment]
Fel infused furies not giving count is most likely a ingame bug. 
If the dungeon run is fast, not all of the imps marked in the imp mother's room have spawned yet. Also imps that blow up with Implosion do not give count.
