### ISSUE TITLE
Upper Karazhan +23

### ISSUE THREAD

**Issue by Holmquists** [nnogga/MethodDungeonTools#28]
In Upper Karazhan you have counted the Boss "Mana devourer" as a mob aswell and it shows up in Upper Library so the Mob Count is not correct. 

First one is with the Extra add (Boss)

https://gyazo.com/26b4fce3ff4e7cac7fba4953f8e7849b

Second one is without Extra add (Boss)

https://gyazo.com/57ab1c92f5cd1bef90a23194e54fca1e

Side note: Awesome addon and keep it up!

**Comment by Seraak** [comment]
the boss is counting for trash count, so its correct

watch this: https://youtu.be/IrZMocDqgWY?t=19m2s
