### ISSUE TITLE
A few features

### ISSUE THREAD

**Issue by niemal** [nnogga/MethodDungeonTools#29]
So, I have a couple ideas about the UI but those are very trivial compared to ones below:

* The ability to highlight crowd control and stun rotation on each pull, along with interrupts. In example, mob A will get imprisoned by the demon hunter; warlock will banish mob B and the shaman will stun first the rest N and then etc. That means you could also have specific interrupt rotations (sephuz procs i.e.) for specific pulls in order to achieve maximum DPS.
* Calculate the minimum required party DPS for each pull given the pull's time length beforehand set by the leader when he is planning the dungeon. This way, you can actually grasp on what truly limits you going higher and how truly DPS cooldowns can be abused in harmony with each other so maximum performance is achieved.
* Combining both ideas above leads to also highlight DPS and healing cooldowns (i.e. battle cry, combustion, trueshot) on each pull for the same reasons explained above.

When people want to push high, they sit down and try to calculate the best course of action, from the first pull till the last; they always try to find different ways to approach the pathing. Having the features above would feel very good.

**Comment by timmywil** [comment]
I was about to suggest the first feature (denote CC on connected mobs), but saw this issue. Would be great to have. Thanks nnogga.
