### ISSUE TITLE
displayed mob HP

### ISSUE THREAD

**Issue by Azaret007** [nnogga/MethodDungeonTools#30]
die HP-Anzeige der Mobs weicht bei mir und einem Gildenkollegen voneinander ab - ich habe die Pulls erstellt (Screenshot1) und der Kollege hat meine erstellen Pulls importiert. Wir haben beide das AddOn heute erst heruntergeladen und erstellt.
![screenshot1](https://user-images.githubusercontent.com/33876304/37257813-336cd4fe-256e-11e8-8791-9a55eb552f89.jpg)
![screenshot2](https://user-images.githubusercontent.com/33876304/37257815-35771688-256e-11e8-91e7-d82572280b35.jpg)
das tritt allerdings nicht nur bei den jetzt im Screenshot aufgeführten Mobs sondern bei allen - auch in anderen Instanzen

**Comment by nnogga** [comment]
please try this again with the newest version, hopefully tracked this issue down
