### ISSUE TITLE
Drag and drop pull order

### ISSUE THREAD

**Issue by koolkiwi** [nnogga/MethodDungeonTools#36]
After creating 30 different pulls and realizing that I need more % it is quick frustrating to add a pull in the middle of the dungeon.

Currently you have to a a new pull #31 
then right click move up one
until you get it to the desired space
repeat.

I suggest that I can just click a pull and drag it to the allocated area.
or if I am clicked on pull 22 and click add new pull it creates #23 and moves the rest by one number.

**Comment by nnogga** [comment]
this is a planned feature and will be implemented

**Comment by brettjacobson** [comment]
drag & drop would be awesome, but at the least, the ability to "Add pull after..." the selected pull (instead of only adding at the end) to insert in the middle would at least make the process easier without drag & drop

**Comment by bht-ts** [comment]
Hey @brettjacobson, you can insert pulls after and before a pull with the context menu of the pull. It is now also possible to merge pulls up and down. 

The development for drag & drop has started today.

**Comment by bht-ts** [comment]
First test is implemented in PullDragDrop branch df9102c

**Comment by nnogga** [comment]
review and merge complete
