### ISSUE TITLE
Why don't mob percentage meters end at 100?

### ISSUE THREAD

**Issue by stevan021** [nnogga/MethodDungeonTools#37]
I've noticed percentages end at 150 and mob that gives 8% usually gives 12% instead. Why is this scaled up like this? ![Picture](https://i.imgur.com/0pmKukQ.png)

**Comment by Fr4gile** [comment]
It not using percentage for mob progress, it uses points AFAIK. If you're using the Angry Keystone addon you will know how this works!

**Comment by stevan021** [comment]
Okay so I guess it doesn't matter, 100% = 150 points then?
