### ISSUE TITLE
Addon stopped working

### ISSUE THREAD

**Issue by Hyperion29** [nnogga/MethodDungeonTools#39]
The minimap icon and the slash command to pull up the Dungeon Tool are not working anymore. Re-install did not fix it, and I'm not sure where this addon stores its saved info to delete the cached info.

**Comment by nnogga** [comment]
Could you install bugsack and buggrabber and post some error logs?

**Comment by Hyperion29** [comment]
Getting nothing from buggrabber and bugsack. I can interact with the minimap button (lock, move), when I click it it does the animation of slightly shrinking, but nothing happens.

**Comment by Hyperion29** [comment]
[bug_report_mdt.txt](https://github.com/nnogga/MethodDungeonTools/files/1849869/bug_report_mdt.txt)

Managed to load the bugs when disabling all other addons. One of my other addons might've been preventing the Lua Errors from going through. Not sure exactly what format to share these in, so I just pasted them into notepad++ and saved as .txt. Let me know if you need them in a different format
