### ISSUE TITLE
Wrong counts in Upper Karazhan

### ISSUE THREAD

**Issue by Octoshape** [nnogga/MethodDungeonTools#40]
When planning a route in upper karazhan, it seemed very strange since the addon told us that we need ALL of the Mana Devourers after the third boss, to be even close to 100%. We then ran the dungeon with the planned route (https://pastebin.com/aN61aSYA) and ended up with way above 100%.

(This might be a similar problem to Issue #25)

**Comment by nnogga** [comment]
did you select the mana devourer (boss) when planning your route? he gives 4 count

**Comment by Octoshape** [comment]
Oh, I was wondering what that single mana devourer to the left was doing there. So that's the boss. I can check when I'm back home.

Usually bosses don't need to be selected, right?

On an unrelated note: Check your Discord PM :)

**Comment by nnogga** [comment]
the pastebin preset is a halls of valor preset

**Comment by Octoshape** [comment]
Whoops, wrong string. https://pastebin.com/5twDTfM9 

That's the one. I am quite sure (not 100%) that this route would yield enough percentage for upper. But I'll have to try it out with a low upper key and a careful group :D

**Comment by Octoshape** [comment]
Ok I just tried it out. I was wrong, your tool is right :D -> closed.
