### ISSUE TITLE
[Maw of Souls] 5 Cursed Falkes at the beginning not all necessarily connected

### ISSUE THREAD

**Issue by timmywil** [nnogga/MethodDungeonTools#41]
If everyone crosses the bridge on the right side, you only get 2 Falkes. Doing this is the high key pull pattern for many groups. I don't know how pedantic to be for things like this since they don't offer count, but might be worth disconnecting them into 2 groups.

**Comment by nnogga** [comment]
Will not unconnect these. Use CTRL select if you only want to select single NPCs.
