### ISSUE TITLE
Few ideas

### ISSUE THREAD

**Issue by Addonman** [nnogga/MethodDungeonTools#44]
-maybe giving some preset pulls for dungeons,maybe a way of ppl of shareing them like weakauras inside or outside a game
-giving shareing pulls to other like in addons silimar  to angry assiments
-would it possialbe to have some sort of arrow in dungeon  or some sort of overlay on minimap to fgive ppl directions to go for certain mobs next

**Comment by xdega** [comment]
You can now, currently, share pulls via an export string (WeakAuras style). But one thing that seems to be lacking at the moment is a place for the community to upload and share pulls. 

@nnogga , are there any plans for a `wago.io`-like platform for sharing pulls? My area of expertise is full-stack web development (primarily PHP/Rails, along with Bootstrap/SASS for Frontend design). 

I would be more than happy to help with such an effort.

**Comment by s4ty** [comment]
It would be really nice to have some sort of arrows between each pull. :)
