### ISSUE TITLE
A few .lua errors that occur with ElvUI

### ISSUE THREAD

**Issue by Wdavis4692** [nnogga/MethodDungeonTools#51]
Visually the tooltips look fine but they seem to throw up .lua errors with ElvUI enabled.
There are no issues if ElvUI is disabled, but it's a popular UI addon so this could potentially affect a lot of users.  An error fires off for every tooltip event, leading to the game recommending addons be disabled due to the volume of errors.  It happens when you mouse over an NPC, generating a tooltip.  The error fires off once upon the tooltip appearing and does not recur until you mouse over another NPC on the map.

Message: ...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1241: attempt to index field '?' (a nil value)
Time: Wed Jul 25 17:17:59 2018
Count: 3
Stack: ...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1241: attempt to index field '?' (a nil value)
(tail call): ?
...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1241: in function <...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1239>
(tail call): ?
...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1831: in function `UpdatePullButtonNPCData'
...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1900: in function `ReloadPullButtons'
...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1492: in function <...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1477>
...Ons\MethodDungeonTools\BattleForAzeroth\Freehold.lua:52: in function `UpdateMap'
...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1518: in function `UpdateToDungeon'
...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1438: in function <...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1431>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...ace\AddOns\HandyNotes\Libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...es\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:442: in function <...es\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:433>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...ace\AddOns\HandyNotes\Libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:351: in function <...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:341>

Locals: <none>

and

Message: ...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:2474: attempt to index field 'Tooltip' (a nil value)
Time: Wed Jul 25 17:23:44 2018
Count: 1
Stack: ...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:2474: attempt to index field 'Tooltip' (a nil value)
[C]: ?
...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:2474: in function <...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:2470>
[C]: in function `Show'
...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:1079: in function `ActivatePullTooltip'
...nTools\AceGUIWidget-MethodDungeonToolsPullButton.lua:46: in function <...nTools\AceGUIWidget-MethodDungeonToolsPullButton.lua:37>

Locals:

**Comment by nnogga** [comment]
What version of the AddOn are you using?

**Comment by Wdavis4692** [comment]
Well spotted -- I was using 2.2.0,  Foolishly forgot to check to see if a newer version is out.  Now I am running 2.2.1  

I am now only getting a single .lua error, again I can confirm it ONLY occurs in conjuction with ElvUI 10.77.  No other addons cause this clash, not even my tooltip addon.

This is the remaining .lua error:

Message: ...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:2551: attempt to index field 'Tooltip' (a nil value)
Time: Wed Jul 25 22:02:39 2018
Count: 7
Stack: ...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:2551: attempt to index field 'Tooltip' (a nil value)
[C]: ?
...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:2551: in function <...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:2547>
[C]: in function `Show'
...terface\AddOns\MethodDungeonTools\DungeonEnemies.lua:215: in function `DisplayBlipTooltip'
...terface\AddOns\MethodDungeonTools\DungeonEnemies.lua:69: in function <...terface\AddOns\MethodDungeonTools\DungeonEnemies.lua:65>

Locals:

**Comment by nnogga** [comment]
It appears you toggled off the Tooltip module in ElvUI. Weird decision by you but the bug will be fixed in the next version.

**Comment by Wdavis4692** [comment]
I disabled the tooltip skinning module because I use TipTac for my tooltips;  Elv's customisation for tooltips is rather poor.  Not that weird :D

Thank you for doing what you can to help.  I appreciate it a lot!
