### ISSUE TITLE
Atal'Dazar - Linked mobs in strange location

### ISSUE THREAD

**Issue by Wdavis4692** [nnogga/MethodDungeonTools#52]
![mdt](https://user-images.githubusercontent.com/31551232/43993125-dbf11f42-9d80-11e8-8762-64812e4a20c6.jpg)

The two mobs "Shieldbearer of Zul" in the lower right, who both give 0 enemy forces, are linked to the pack directly before Vol'kaal.  The screenshot illustrates them by their numbers showing on their icons as I point the cursor at them.  Selecting either location of adds will also select the entire group on the opposite side of the instance.

If this is intentional then I apologise but it seemed strange so I reported it.

**Comment by nnogga** [comment]
please update to 2.2.18
