### ISSUE TITLE
Wrong data: Shring of Stroms - Lord Stormsong

### ISSUE THREAD

**Issue by bht-ts** [nnogga/MethodDungeonTools#54]
Hey,
I used MDT for the spell ID's to create all my WA's. I found that Lord Stormsong shall have a spell called "Mystic Touch", which does exactly the same as the Monk debuff does. Pretty sure, that there something went wrong and it shouldn't be there. Haven't tested it, but it does matches the style of his other abilities. 

Best regards,
Dradux

**Comment by nnogga** [comment]
fixed in 2bcbf011c843e859e0f34eff722b6bfcc6946588
