### ISSUE TITLE
Feature Request: Boss % Check

### ISSUE THREAD

**Issue by MMA92** [nnogga/MethodDungeonTools#57]
If you kill a Boss, check if you have managed to get enough "mob percentage".
E.g. if you forget to pull a certain group and miss percentage .

**Comment by giuliano0** [comment]
That would be, I think, the ability to add a checkpoint marker to the map. In general, add markers with text notes for arbitrary, player input information, including e.g. skips, pot use, or even completeness checkpoints. Anything text allows, really :P

But for now, you can alleviate the lack of such feature by drawing on the map I guess.

**Comment by nymann** [comment]
@giuliano0 you can't tie anything with a position inside a dungeon, so general location markers won't fly.
However, you can easily do what @MMA92 asks, by matching the boss ID with the current target, and then from there display the planned count.

**Comment by giuliano0** [comment]
@nymann I mean you can use notes, something the addon already has implemented, to set up stuff like how much enemy percentage you should get up to a certain boss.

Another thing you can already do is to simply mouseover a pull you set and that will show you, at the enemy forces bar inside the addon, how much you got up to that pull you are hovering.

Those do *not* correspond to the feature @MMA92 is asking for, I just wanted to point out there are alternatives.

I think the requested feature would be a nice touch to the addon, though, but in the "nice to have" category at most.
