### ISSUE TITLE
Shrine of the Storm % counter

### ISSUE THREAD

**Issue by Tryllemann** [nnogga/MethodDungeonTools#58]
It looks like the % counter for trash mobs is wrong. 
Up to second boss, for my route it should be 74%, but addon shows 54%

**Comment by Wdavis4692** [comment]
Interestingly it shows a higher forces requirement on non-teeming weeks.  We just ran shrine and reached 100% quite early through lots of body pulls.  Selecting the same trash on MDT claimed we were nowhere near 100% forces.

**Comment by schipp** [comment]
Can also confirm. We ended up pulling 483/662 (according to MDT), which was just a bit above 100%. Don't know if total required or enemy forces of some pulls changed.

**Comment by Wdavis4692** [comment]
OK on inspection the forces requirements are correct, the thing is the cultists on the bridge give 9 forces, not 6.   Colossal Tentacles give 10, not 7.  Abyssal Eels give 3, not 2. Forgotten Denizens give 9, not 6.  The Sunken Denizen gives 13, not 9.

**Comment by Wdavis4692** [comment]
I have worked out all the correct forces requirements, here is the updated .lua file for Shrine of the Storm which goes in the MethodDungeonTools/BattleForAzeroth folder:

https://1drv.ms/u/s!ArYur3HGpT6AhIowEFYPwen60jN2uQ

**Comment by Wdavis4692** [comment]
Apologies, the last file was the wrong one.  https://1drv.ms/u/s!ArYur3HGpT6AhIowetL0nrMLDuli7w should have much more accurate enemy forces on it.  Compared to my run today, it's only 1 enemy force off by the point I reached the last boss.  Not sure what that might be.

**Comment by nnogga** [comment]
fixed in 8534195620077d5b325972750cf004f472129928 thanks for the reports
