### ISSUE TITLE
Siege of Boralus Alliance Support

### ISSUE THREAD

**Issue by Wdavis4692** [nnogga/MethodDungeonTools#59]
Hi -- Are there any plans to introduce Siege of Boralus support for alliance?  Our route, and therefore trash allocation up to the first boss - is different.  From the first boss onward, everything is the same.

**Comment by nnogga** [comment]
yes, coming in the following weeks

**Comment by nnogga** [comment]
implemented in 9bdb38574e174e3a68a79c52c099c4870be03fea
