### ISSUE TITLE
Kings' Rest / Incorrect values on the Progress Bar / Affix: Teeming

### ISSUE THREAD

**Issue by oloking** [nnogga/MethodDungeonTools#60]
Hello,
The progress bar on Kings' Rest with the Affix: Teeming might be incorrect.
The Value should be usually higher.
![wowscrnshot_092218_005628](https://user-images.githubusercontent.com/43484859/45909847-c770b880-be04-11e8-8876-3a1929cf3d12.jpg)

**Comment by nnogga** [comment]
fixed in 3c6c616009b02f0ff79965ecbbf70e8cf0f3a807
