### ISSUE TITLE
Shrine of the Storms - Teeming - Wrong %

### ISSUE THREAD

**Issue by vsoraas** [nnogga/MethodDungeonTools#61]
Counting all the packs in Vol'zith's room - 4 packs of Abyssal Eels + the pack on land - we're given 21.6% forces in the tool. This is off in the negative by somewhere in the neighborhood of 4%. We had ~80% after Stormsong, and we sat at ~96.5% after clearing the room.

Part of this might be due to Abyssal Eel being listed at 0.5% in MDT, which seems to be too high. AngryKeystones tooltip has it listed as 0.38% in-game. If this discrepancy is real, it would account for a difference of 3.84%.

**Comment by nnogga** [comment]
fixed in 1673dcee251a43bbc7d8eb7472f4005e34e88e9f
