### ISSUE TITLE
LibUIDropDownMenu lua errors

### ISSUE THREAD

**Issue by ir2000** [nnogga/MethodDungeonTools#62]
Multiple LUA error when other addons use this library.

Deferred XML Node object named L_UIDropDownMenuButtonTemplate already exists
Deferred XML Node object named L_UIDropDownCustomMenuEntryTemplate already exists
Deferred XML Node object named L_UIDropDownMenuTemplate already exists
Deferred XML Node object named L_UIDropDownListTemplate already exists

Seems related to this https://www.wowace.com/projects/libuidropdownmenu/issues/1

I updated manually to the latest version of the lib and the errors were gone.

**Comment by nnogga** [comment]
pushed a new version with updated lib eee9f9792726d352a47dd53188884e484f50b1f1 please check if this fixes the issue
