### ISSUE TITLE
Share link broken with Prat.

### ISSUE THREAD

**Issue by Joey-Robinson** [nnogga/MethodDungeonTools#63]
Using Prat, I'm unable to click any share links provided with MDT. When I disable Prat, similar to sharing WA's, I'm able to click and import. Even updating Prat doesn't fix this issue. 
`|HMethodDungeonTools-User-Server[User-Server - Shrine of the Storm: Default]`

Is the output (name changed, of course.) Any suggestions on how to fix would be 👍

**Comment by xdega** [comment]
This looks like an issue with Prat improperly parsing the link in chat.

Other people are also experiencing the issue:
https://www.curseforge.com/wow/addons/prat-3-0?comment=4618
https://www.wowace.com/projects/prat-3-0/issues/31263

**Comment by nnogga** [comment]
prat issue
