### ISSUE TITLE
Sugestion: Freehold Join Crew

### ISSUE THREAD

**Issue by Tryllemann** [nnogga/MethodDungeonTools#64]
Would like a option to manually add a step from where Join Crew is activated.
Or add a feature where we can add in "Add pull" a fixed manually kill percentage upto that step.

I personally clear all trash before activating Join Crew on second boss, since waiting for BL/Hero debuff.
That means we kill alot of trash without join crew, and then some groups with Join crew.
So like this, on teeming i have 72.5% after second boss. Not 58.8% like i get when activation Join Crew.

**Comment by nnogga** [comment]
You can select mobs that you wish to kill with join crew left unchecked. After checking "Join Crew" the previously selected mobs are still part of your pulls even though they are not selectable anymore.

**Comment by Tryllemann** [comment]
Yes, but the kill % is wrong. 
See now that i can just toggle Join Crew to check real %.
Since the groups pulled after join crew was selected, thos mobs are left out on %.
Nice 👍

**Comment by nnogga** [comment]
I don't quite understand. Did this fix your problem or is there something wrong in the AddOn still?
