### ISSUE TITLE
Full screen option / resizeable window

### ISSUE THREAD

**Issue by Gnarfoz** [nnogga/MethodDungeonTools#71]
First off, thanks for this fantastic addon and all the hard work that went into making it!

I have a small feature suggestion (or not so small, judging from my own attempts to make this a pull request instead):

Even though the map itself is zoomable and scrollable, the addon window is rather small.
My aging eyes are having a bit of a hard time making out details while the map is zoomed out.
And zooming in of course quickly makes one lose track of the bigger picture.

Could you make the window resizeable (a draggable corner would be awesome), or add a fullscreen option?
So far, I have only really used the addon before a run, to coordinate what we are _going to_ do once the run starts. Obscuring the entire screen would probably not be a big problem at that point in time.

Now, I have tried making this change myself, but I got stuck when I realized that the map pin positions seem to be saved as pixel positions and are thus dependent upon the window being the original size.
I could not find a suitable (or any, for that matter) spot to scale their coordinates for my modified window size.

So they end up looking all tiny and lost. ;-)
![image](https://user-images.githubusercontent.com/65654/47323092-aa751280-d65a-11e8-8ce9-131ebcfa37ca.png)

I resized the window like this:
https://github.com/Gnarfoz/MethodDungeonTools/commit/1b64b3540b4b6e2f5b3e9ea3025d4075a7ce577f

Thanks again.

**Comment by nnogga** [comment]
Implemented in 2.8.2
