### ISSUE TITLE
Count is off for a few dungeons

### ISSUE THREAD

**Issue by Musouv** [nnogga/MethodDungeonTools#78]
Heart Guardians at the end of temple give 6 count each, rather than 4

Motherlode was recently hotfixed to require only 384 count and earthshapers in the second area now only count for 4 instead of 8

Freehold Deckhands and Shipmates are slightly off as well, the deckhands have significantly lower hp, but are worth 1, while shipmates have more hp and are worth 2 each

**Comment by Musouv** [comment]
Thanks for the count fix on temple and motherlode!
Freehold count is still slightly off but it's very minor

**Comment by nnogga** [comment]
freehold and temple are also fixed now

**Comment by Musouv** [comment]
I may have been a bit unclear in my original comment, when I originally made the comment, heart guardians in MDT at the end of temple were being valued at 4 in MDT when in actuality they give 6 count in-game, then by my second comment, they had already been fixed to be worth 6. It seems as though in the latest update they have been reduced to 4 again in MDT when they should be 6.

Freehold counts are correct now after the fix though, thanks!
