### ISSUE TITLE
Wrong displayed Group Siege of Boralus

### ISSUE THREAD

**Issue by hermuth** [nnogga/MethodDungeonTools#83]
Hey,

on alliance side and while Teeming affix the group G55 consists of 2x Riptide Shredder, 1x Blacktar Bomber, 1x Scrimshaw Enforcer, 1x Dockhound Packmaster, 1x Snarling Dockhound (last two are neither of the patrols G56 and G57). But in the dungeon tool are only 2x Riptide Shredder, 1x Blacktar Bomber displayed, like in non-Teeming weeks.

**Comment by nnogga** [comment]
this will be fixed in the next version
