### ISSUE TITLE
Count errors again in Motherlode and Temple

### ISSUE THREAD

**Issue by Musouv** [nnogga/MethodDungeonTools#84]
Heart Guardians at the end of Temple of Sethraliss on the bridge to final boss should be worth 6, but are currently displayed as being worth 4.

Motherlode Teeming count total is incorrect, should be 460 but displays as 499.

**Comment by nnogga** [comment]
motherlode teeming count is fixed in an upcoming version, i need video proof of heart guardians giving 6 count (not tooltip screenshots of another AddOn saying something different)

**Comment by Musouv** [comment]
I usually have 18 count remaining with last boss and pull everything on bridge except one heart guardian to get the exact count, which adds up, here's a clip from one of my group that should show it going from 206 -> 212 -> 218 count when we kill 2 heart guardians back to back
https://www.youtube.com/watch?v=_ObKN32JH9s

**Comment by nnogga** [comment]
fixed in version 2.7.0
