### ISSUE TITLE
Conflict with another addon

### ISSUE THREAD

**Issue by Ngml** [nnogga/MethodDungeonTools#87]
Hello, If you're using "MDT" in combination of "O item level (Oilvl)" addon, for some reason you can't choose colors for your pulls, also most of the right click menu options are simply empty (including color selection)

**Comment by nnogga** [comment]
OIlvl is the problem here, it's using an outdated version of a library which conflicts with many AddOns. Issue has been reported to the creator of OIlvl but no response has been received.
