### ISSUE TITLE
SetTargetClampingInsets error

### ISSUE THREAD

**Issue by Hemario** [nnogga/MethodDungeonTools#89]
19x [ADDON_ACTION_BLOCKED] AddOn 'MethodDungeonTools' tried to call the protected function 'SetTargetClampingInsets()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetTargetClampingInsets'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:273: in function `SetupClassNameplateBars'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:96: in function `OnNamePlateAdded'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:51: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:42>

Locals:
InCombatSkipped

**Comment by nnogga** [comment]
not related to MDT
