### ISSUE TITLE
Share function not working

### ISSUE THREAD

**Issue by Sniqi** [nnogga/MethodDungeonTools#94]
Hi,

seems like I have a rare bug on my machine?

Links created with the "share" button are empty and do not contain the content it should have.
I can click links from other people with no problems.

Tested in this environment:
-english client
-MDT freshly installed
-MDT is the only addon active and installed
-fresh WTF folder
-scan & repair for WoW completed
-all background apps related to WoW closed

This bug startet with patch 8.2

This error comes straight, when logging in/reloading:

> 1x MethodDungeonTools\Transmission.lua:182: attempt to concatenate local 'realm' (a nil value)
> MethodDungeonTools\Transmission.lua:182: in function `SetHyperlink'
> FrameXML\ItemRef.lua:395: in function <FrameXML\ItemRef.lua:11>
> ...aceBlizzard_CombatLog\Blizzard_CombatLog.lua:3513: in function `SetItemRef'
> FrameXML\ChatFrame.lua:3721: in function `ChatFrame_OnHyperlinkShow'
> [string "*:OnHyperlinkClick"]:1: in function <[string "*:OnHyperlinkClick"]:1>

This error comes, when clicking the not functioning link from "share":

> Locals:
> self = ItemRefTooltip {
>  0 = <userdata>
>  updateTooltip = 0.200000
>  shoppingTooltips = <table> {
>  }
>  TopOverlay = <unnamed> {
>  }
>  SetHyperlink = <function> defined @MethodDungeonTools\Transmission.lua:177
>  needsReset = true
>  BottomOverlay = <unnamed> {
>  }
>  updateTooltipTime = 0
>  UpdateTooltip = <function> defined *:OnLoad:5
> }
> link = "MethodDungeonTools-SniqíAntonidas"
> sender = "SniqíAntonidas"
> name = nil
> realm = nil
> (*temporary) = nil
> (*temporary) = "-"
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "attempt to concatenate local 'realm' (a nil value)"
> OriginalSetHyperlink = <function> defined =[C]:-1

Thanks for your help

**Comment by Sniqi** [comment]
addition: this is only happening with my char Sniqí-Antonidas. My char Sniqi-Antonidas is working for example. (with the exact same environment)

**Comment by nnogga** [comment]
a fix for this is in the works, thanks for the report

**Comment by grosters** [comment]
180:   ... string.match(sender,"(%u%l*)%-*(%u%a*)")
this %u and %l now broken and  doesnt work for any non english cymbols?! thanks blizzard...

**Comment by nnogga** [comment]
fixed in version 2.7.0
