### ISSUE TITLE
MDT Comment Box

### ISSUE THREAD

**Issue by Trid3nt1** [nnogga/MethodDungeonTools#96]
I've tried fiddling HARD with ElvUI assuming it was that, that was making this happen but I just cannot figure it out. Hoping to put this here in case a dev or community member has had the same problem before and has a fix.

[![Screenshot from Gyazo](https://gyazo.com/ee9b566067e2037e4e1585230a65c123/raw)](https://gyazo.com/ee9b566067e2037e4e1585230a65c123)

**Comment by Trid3nt1** [comment]
Sorry, forgot to explain the issue.. that box is all you get. You can't click into it, you can't just type and hope it'll enter into the box - It's just an empty square with an accept button.

**Comment by nnogga** [comment]
fixed in version 2.7.0
