### ISSUE TITLE
Share function not working rus client

### ISSUE THREAD

**Issue by Fantozi** [nnogga/MethodDungeonTools#97]
Функция SHARE не работает для русско язычных аккаунтов, ссылка в чате появляется но она не кликабельна.

The SHARE function does not work for Russian-language accounts, the link in the chat appears but it is not clickable.

**Comment by Fantozi** [comment]
Пробовал выключать все аддоны кроме МДТ, результат тот же.

**Comment by nnogga** [comment]
fixed in v2.7.5
