### ISSUE TITLE
No emissaries shown in Siege of Boralus - MDT v2.7.5

### ISSUE THREAD

**Issue by zmoose** [nnogga/MethodDungeonTools#98]
Updated to MDT version 2.7.5 and created a new siege of borallus route for horde doesn't show any emissaries for week 3 affixes.

**Comment by zmoose** [comment]
![image](https://user-images.githubusercontent.com/10065577/63123440-99411d80-bf6e-11e9-9af5-6734067ba6e1.png)

**Comment by nnogga** [comment]
fixed in 2.7.6
