### ISSUE TITLE
Inaccurate Mob Counts

### ISSUE THREAD

**Issue by Trid3nt1** [nnogga/MethodDungeonTools#99]
It seems if you create a new Route based off of a route that includes different Emissaries, the new copied route with the correct affix rotation checked will still have the emissaries from the original route selected, but they're hidden. Couple that with selecting the new emissaries - You end up with an incorrect mob count

**Comment by Trid3nt1** [comment]
In case this "bug" is specific to a Dungeon, I'm currently working on a route for this weeks affixes in Siege. Not sure if it effects other Dungeon maps.

**Comment by nnogga** [comment]
fixed
